/* ===== Shared engine for the Integral *-Start-Here explainers =====
   Generated by integral-start-here/build.py from the CDS template. Do not edit by hand;
   edit CDS-Start-Here/index.html (the template) or build.py, then re-run the build.
   Loads BEFORE each module's data.js (which defines REF/STATUS/OBJECTS/STEPS/META). */

// ----- provenance tag helper -----
const TAG = {WP:"t-wp", DG:"t-dg", DEFERRED:"t-def", FED:"t-fed"};
function tag(t){return '<span class="tag '+(TAG[t]||"")+'">'+t+'</span>';}
function lnk(u,t){return '<a href="'+u+'" target="_blank" rel="noopener">'+t+'</a>';}
function LSPEC(p){return '<a href="https://github.com/tairea/integral-data-start-here/blob/main/integral-schema-exercise/'+p+'" target="_blank" rel="noopener"><code>'+p+'</code></a>';}

const SHELL = `
<div class="app">
  <header>
    <button class="menubtn" id="menuL" onclick="togglePanel('nav')" aria-label="Open steps menu" title="Steps menu">☰</button>
    <h1 id="htitle"></h1>
    <span class="sub" id="hsub"></span>
    <div class="prog">
      <div>Step <b id="stepnum">1</b> / <span id="steptot">13</span></div>
      <div class="pbar"><i id="pbar"></i></div>
    </div>
    <button class="menubtn" id="menuR" onclick="togglePanel('data')" aria-label="Open data panel" title="The data so far">▦</button>
  </header>

  <div id="backdrop" onclick="closePanels()"></div>

  <nav id="nav"></nav>

  <main><div class="wrap" id="content"></div></main>

  <aside>
    <h3>The data so far</h3>
    <p class="hint2" id="phint"></p>
    <div class="issue-card" id="issuecard" style="display:none">
      <div class="iid" id="iid">stillwater:ISS-001</div>
      <div id="sobjname" style="font-size:13px;margin:3px 0 2px"></div>
      <div id="senum" style="color:var(--mut);font-size:11.5px"></div>
      <div class="statustrack" id="statustrack"></div>
    </div>
    <h3 style="margin-top:6px">Objects in play</h3>
    <div class="objlist" id="objlist"></div>
    <div class="legend">
      <div><span class="dotc ratified" style="display:inline-block"></span> has a JSON-Schema contract (simulator-validated)</div>
      <div><span class="dotc proposed" style="display:inline-block"></span> proposed shape (no schema yet — help wanted)</div>
      <div style="margin-top:6px;opacity:.85">Both are candidate — neither is community-ratified.</div>
    </div>
  </aside>

  <footer>
    <button class="btn ghost" id="back">← Back</button>
    <button class="btn" id="next">Next →</button>
    <span class="hint">Tip: use ← → arrow keys. Everything here is real output from the simulator.</span>
  </footer>
</div>

`;

let i = 0, content, navEl, visited;



// ===================================================================== render




function navTree(){
  let html = "", lastGrp = null;
  STEPS.forEach((s, idx)=>{
    if(s.group !== lastGrp){ html += '<div class="grp">'+s.group+'</div>'; lastGrp = s.group; }
    const cls = (idx===i?"on":"") + (visited.has(idx)&&idx!==i?" done":"");
    const dot = visited.has(idx) ? (idx===i?"▸":"✓") : "·";
    html += '<button class="'+cls+'" onclick="go('+idx+')"><span class="dot">'+dot+'</span>'+s.nav+'</button>';
  });
  navEl.innerHTML = html;
}

function fieldRows(o){
  return o.fields.map(f=>{
    const tags = (f.t||[]).map(tag).join(" ");
    const st = f.s==="new" ? '<span class="tag t-new">new</span>' : f.s==="updated" ? '<span class="tag t-upd">updated</span>' : "";
    const cls = f.s==="new" ? "new" : f.s==="updated" ? "upd" : "";
    const ty = f.ty ? `<span class="ftype">${f.ty}</span>` : "";
    const tail = (tags || st) ? ` <span class="ftags">${tags}${tags && st ? " " : ""}${st}</span>` : "";
    return `<div class="field ${cls}"><span class="fn"><code>${f.fn}</code>${ty}</span><span class="fnote">${f.note}${tail}</span></div>`;
  }).join("");
}

function tagKeyBody(){
  return '<div class="keybody">'+
    tag("WP")+' — from the White Paper &nbsp; '+tag("DG")+' — devguide addition<br>'+
    tag("DEFERRED")+' — reserved, populated later &nbsp; '+tag("FED")+' — federation field (mostly empty until nodes connect)<br>'+
    '<span class="tag t-new">new</span> — created at this step &nbsp; <span class="tag t-upd">updated</span> — changed at this step</div>';
}
function keyExpand(){ return `<details class="keyexp"><summary>What do the tags mean?</summary>${tagKeyBody()}</details>`; }

// ----- mobile panel toggles -----
function togglePanel(which){
  const el = which==='nav' ? document.querySelector('nav') : document.querySelector('aside');
  const other = which==='nav' ? document.querySelector('aside') : document.querySelector('nav');
  const open = el.classList.toggle('open');
  other.classList.remove('open');
  document.getElementById('backdrop').classList.toggle('on', open);
}
function closePanels(){
  document.querySelector('nav').classList.remove('open');
  document.querySelector('aside').classList.remove('open');
  document.getElementById('backdrop').classList.remove('on');
}

function copyRef(text, btn){
  let ok=false;
  try{                                   // synchronous, works on a real click incl. file://
    const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';
    document.body.appendChild(t);t.focus();t.select();
    ok=document.execCommand('copy');t.remove();
  }catch(e){ ok=false; }
  if(!ok && navigator.clipboard){ try{ navigator.clipboard.writeText(text); ok=true; }catch(e){} }
  const o=btn.textContent; btn.textContent = ok ? "✓ copied!" : "⧉ select & copy ↓";
  setTimeout(()=>{ btn.textContent=o; }, 1700);
}
function copyFoot(ref){
  const safe = ref.replace(/\\/g,"\\\\").replace(/'/g,"\\'");
  return `<div class="cardfoot"><button class="copybtn" onclick="copyRef('${safe}', this)">📋 Copy for Discord</button><code class="reftext">${esc(ref)}</code></div>`;
}

function objCard(o, key, slug){
  const hasSchema = o.contract && o.contract.indexOf("schemas")===0;
  const pill = hasSchema
    ? `<span class="pill ratified">proposed json-schema ${LSPEC(o.contract)} (simulator-validated)</span>`
    : `<span class="pill proposed">proposed shape — no schema written yet</span>`;
  const k = (typeof META!=='undefined' && META.key) || 'cds';
  const ref = hasSchema ? `${k}-${slug} ${o.contract}` : `${k}-${slug} ${o.type} (proposed shape — no schema yet)`;
  return `
   <div class="obj">
     <div class="ohead">
       <span class="otype">${o.type}</span>
       ${pill}
       <span class="tabs">
         <button class="on" data-tabbtn="${key}" data-which="fields" onclick="showtab('${key}','fields')">Plain-language fields</button>
         <button data-tabbtn="${key}" data-which="json" onclick="showtab('${key}','json')">Actual object (JSON)</button>
       </span>
     </div>
     <div data-pane="${key}" data-which="fields">${fieldRows(o)}</div>
     <div data-pane="${key}" data-which="json" hidden><pre>${esc(o.json||"")}</pre></div>
     ${keyExpand()}
     ${copyFoot(ref)}
   </div>`;
}

function showtab(key, which){
  document.querySelectorAll('[data-pane="'+key+'"]').forEach(p=>{ p.hidden = (p.dataset.which!==which); });
  document.querySelectorAll('[data-tabbtn="'+key+'"]').forEach(b=>b.classList.toggle('on', b.dataset.which===which));
}

// ----- M1 submission picker (8 distinct Submission objects, click to inspect) -----
function subJson(sub){
  return JSON.stringify({
    submission_id:"stillwater:"+sub.id, issue_id:"stillwater:ISS-001", node_id:"stillwater",
    author_id:"stillwater:"+sub.who.toLowerCase(), type:"concern", content:sub.content,
    duplicate_of: sub.dup ? ("stillwater:"+sub.dup) : null, embedding:null
  }, null, 2);
}
function selectSub(idx){
  const subs=window.__SUBS||[], x=subs[idx]; if(!x) return;
  const el=document.getElementById('sub-json'); if(el) el.textContent=subJson(x);
  document.querySelectorAll('[data-subchip]').forEach(b=>b.classList.toggle('on', +b.dataset.subchip===idx));
  showtab('sub','json');
}
function submissionSection(s, slug){
  const subs=s.submissions; window.__SUBS=subs;
  const chips=subs.map((x,idx)=>`<button class="subchip${idx===0?' on':''}${x.dup?' dup':''}" data-subchip="${idx}" onclick="selectSub(${idx})">${x.id} · ${x.who}${x.dup?'<span class="dupb">→ dup of '+x.dup+'</span>':''}</button>`).join("");
  const o=s.submissionObj, ref=`${(typeof META!=='undefined' && META.key) || 'cds'}-${slug} ${o.contract}`;
  return `
   <p class="note">The eight raw submissions — click any to inspect its object. Three are near-duplicate "cut off" reports (dashed) that M1 links to a canonical entry:</p>
   <div class="picker">${chips}</div>
   <div class="obj">
     <div class="ohead"><span class="otype">Submission</span>
       <span class="pill ratified">proposed json-schema ${LSPEC(o.contract)} (simulator-validated)</span>
       <span class="tabs">
         <button class="on" data-tabbtn="sub" data-which="fields" onclick="showtab('sub','fields')">Plain-language fields</button>
         <button data-tabbtn="sub" data-which="json" onclick="showtab('sub','json')">Actual object (JSON)</button>
       </span></div>
     <div data-pane="sub" data-which="fields">${fieldRows(o)}</div>
     <div data-pane="sub" data-which="json" hidden><pre id="sub-json">${esc(subJson(subs[0]))}</pre></div>
     ${keyExpand()}
     ${copyFoot(ref)}
   </div>`;
}

function renderModule(s){
  const slug = s.nav.replace('·',' ').replace(/\s+/g,' ').trim().toLowerCase().replace(/\s+/g,'-');
  const objs = s.objects ? s.objects : [Object.assign({}, s.object, {json: s.jsonPeek})];
  const cards = objs.map((o, idx)=>objCard(o, (s.mod||s.badge)+'-'+idx, slug)).join("");
  return `
   <span class="badge">${s.badge}</span>
   <h2>${s.title}</h2>
   <p class="job">${s.job}</p>
   <div class="sec"><div class="lbl">📖 The story</div><p>${s.story}</p></div>
   <div class="sec"><div class="lbl">👥 What the community does</div><p>${s.community}</p>
     ${s.submissions ? submissionSection(s, slug) : ""}
   </div>
   <div class="sec"><div class="lbl">📦 The data created / updated</div><p>${s.dataIntro}</p>
     ${cards}
   </div>
   <div class="sec"><div class="lbl">➡️ Handoff to the next step</div><p>${s.handoff}</p></div>
   <div class="sec"><div class="lbl">📚 Provenance</div><p class="prov">${s.prov}</p></div>
   ${s.check ? checkBox(s) : ""}
  `;
}

function checkBox(s){
  const id = "chk-"+(s.mod||s.badge);
  return '<div class="check" id="'+id+'"><div class="q">🤔 '+s.check.q+'</div>'+
    '<button onclick="document.getElementById(\''+id+'\').classList.add(\'show\')">Show answer</button>'+
    '<div class="a">'+s.check.a+'</div></div>';
}

function esc(t){return t.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}

function render(){
  const s = STEPS[i];
  content.innerHTML = s.kind==="module" ? renderModule(s)
    : '<span class="badge">'+s.badge+'</span><h2>'+s.title+'</h2>'+s.body;
  content.parentElement.scrollTop = 0;
  document.getElementById("stepnum").textContent = i+1;
  document.getElementById("steptot").textContent = STEPS.length;
  document.getElementById("pbar").style.width = ((i+1)/STEPS.length*100)+"%";
  document.getElementById("back").disabled = i===0;
  document.getElementById("next").disabled = i===STEPS.length-1;
  navTree();
  renderPanel();
}

// ---- persistent "data so far" panel ----
function currentModule(){ // highest module number reached by current step
  let m = 0;
  for(let k=0;k<=i;k++){ if(STEPS[k].kind==="module") m = Math.max(m, STEPS[k].mod); }
  return m;
}
function renderPanel(){
  const m = currentModule();
  const issuecard = document.getElementById("issuecard");
  issuecard.style.display = m>=1 ? "block" : "none";
  // status track: status index = module number-1 (M1→intake … M8→dispatched)
  const curStatus = m>=1 ? Math.min(m,STATUS.length)-1 : -1;
  document.getElementById("statustrack").innerHTML = STATUS.map((st,idx)=>{
    const c = idx<curStatus?"done":idx===curStatus?"cur":"";
    return '<span class="stchip '+c+'">'+st+'</span>';
  }).join("");
  // objects
  document.getElementById("objlist").innerHTML = OBJECTS.map(o=>{
    const live = m>=o.at, fresh = o.at===m;
    const cls = "objrow"+(live?" live":"")+(fresh?" fresh":"");
    return '<div class="'+cls+'"><span class="dotc '+o.tier+'"></span>'+o.type+
           '<span class="ocount">×'+o.count+(fresh?' · new':'')+'</span></div>';
  }).join("");
}

function go(n){ i = Math.max(0, Math.min(STEPS.length-1, n)); visited.add(i); render(); closePanels(); }

function initStartHere(){
  document.getElementById('approot').innerHTML = SHELL;
  const plain = META.title.replace(/<[^>]+>/g,'');
  document.title = plain + ' — Integral';
  document.getElementById('htitle').textContent = META.emoji + '  ' + plain;
  document.getElementById('hsub').textContent = META.sub;
  document.getElementById('phint').innerHTML = META.panelHint;
  document.getElementById('iid').textContent = META.statusObjectId;
  document.getElementById('sobjname').textContent = META.statusObjectName + ' object';
  document.getElementById('senum').textContent = 'status lifecycle (' + META.statusEnumName + ' enum):';
  content = document.getElementById('content'); navEl = document.getElementById('nav');
  visited = new Set([0]);
  document.getElementById('next').onclick = ()=>go(i+1);
  document.getElementById('back').onclick = ()=>go(i-1);
  document.addEventListener('keydown', e=>{ if(e.key==='ArrowRight')go(i+1); if(e.key==='ArrowLeft')go(i-1); });
  render();
}
window.addEventListener('DOMContentLoaded', initStartHere);
