#!/usr/bin/env python3
"""Build the shared engine for the Integral *-Start-Here explainers, and (re)generate each
module's thin index.html from its data.js.

Source of truth: CDS-Start-Here/index.html is the *template* — the part between DATA_START and
DATA_END is per-system content (extracted to CDS-Start-Here/data.js); the rest becomes the shared
engine.css + engine.js here. Other modules supply only their own data.js.

Run from anywhere:  python3 Integral-Data-Start-Here/build.py
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HUB = os.path.join(ROOT, "Integral-Data-Start-Here")
TEMPLATE = os.path.join(ROOT, "CDS-Start-Here", "index.html")
MODULE_DIRS = ["CDS-Start-Here", "OAD-Start-Here", "ITC-Start-Here", "COS-Start-Here", "FRS-Start-Here"]

THIN_INDEX = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Start Here — Integral</title>
<link rel="stylesheet" href="../Integral-Data-Start-Here/engine.css">
</head>
<body>
<div id="approot"></div>
<script src="../Integral-Data-Start-Here/engine.js"></script>
<script src="data.js"></script>
</body>
</html>
"""


def extract_engine():
    text = open(TEMPLATE, encoding="utf-8").read()
    css = re.search(r"<style>(.*?)</style>", text, re.S).group(1)
    body = re.search(r"<body>(.*?)<script>", text, re.S).group(1)
    script = re.search(r"<script>(.*?)</script>", text, re.S).group(1)

    i_ds = script.index("/* ============ DATA_START")
    i_gh = script.index("const GH_DG=")
    i_de = script.index("/* ============ DATA_END")
    engine_pre = script[:i_ds].rstrip()                 # TAG/tag/lnk/LSPEC
    data_block = script[i_gh:i_de].rstrip()             # GH/REF/STATUS/OBJECTS/STEPS/META
    engine_post = script[script.index("*/", i_de) + 2:] # render funcs + wiring

    # strip the parse-time state decls + trailing event wiring (moved into initStartHere)
    engine_post = engine_post.replace("let i = 0;", "")
    engine_post = engine_post.replace(
        'const content = document.getElementById("content"), navEl = document.getElementById("nav");', "")
    engine_post = engine_post.replace("const visited = new Set([0]);", "")
    wire = engine_post.index('document.getElementById("next").onclick')
    engine_funcs = engine_post[:wire].rstrip()

    # build the shell template with ids the engine fills from META
    shell = body
    shell = re.sub(r"<h1>.*?</h1>", '<h1 id="htitle"></h1>', shell, count=1, flags=re.S)
    shell = re.sub(r'<span class="sub">.*?</span>', '<span class="sub" id="hsub"></span>', shell, count=1, flags=re.S)
    shell = re.sub(r'<p class="hint2">.*?</p>', '<p class="hint2" id="phint"></p>', shell, count=1, flags=re.S)
    shell = shell.replace('<div style="font-size:13px;margin:3px 0 2px">Issue object</div>',
                          '<div id="sobjname" style="font-size:13px;margin:3px 0 2px"></div>')
    shell = shell.replace('<div style="color:var(--mut);font-size:11.5px">status lifecycle (IssueStatus enum):</div>',
                          '<div id="senum" style="color:var(--mut);font-size:11.5px"></div>')

    engine_js = f"""/* ===== Shared engine for the Integral *-Start-Here explainers =====
   Generated by Integral-Data-Start-Here/build.py from the CDS template. Do not edit by hand;
   edit CDS-Start-Here/index.html (the template) or build.py, then re-run the build.
   Loads BEFORE each module's data.js (which defines REF/STATUS/OBJECTS/STEPS/META). */
{engine_pre}

const SHELL = {js_str(shell)};

let i = 0, content, navEl, visited;

{engine_funcs}

function initStartHere(){{
  document.getElementById('approot').innerHTML = SHELL;
  const plain = META.title.replace(/<[^>]+>/g,'');
  document.title = plain + ' — Integral';
  document.getElementById('htitle').textContent = META.emoji + '  ' + plain;
  document.getElementById('hsub').textContent = META.sub;
  document.getElementById('phint').innerHTML = META.panelHint;
  document.getElementById('iid').textContent = META.statusObjectId;
  document.getElementById('sobjname').textContent = META.statusObjectName + ' object';
  document.getElementById('senum').textContent = 'status lifecycle (' + META.statusEnumName + ' enum):';
  content = document.getElementById('content'); navEl = document.getElementById('nav');
  visited = new Set([0]);
  document.getElementById('next').onclick = ()=>go(i+1);
  document.getElementById('back').onclick = ()=>go(i-1);
  document.addEventListener('keydown', e=>{{ if(e.key==='ArrowRight')go(i+1); if(e.key==='ArrowLeft')go(i-1); }});
  render();
}}
window.addEventListener('DOMContentLoaded', initStartHere);
"""
    open(os.path.join(HUB, "engine.css"), "w", encoding="utf-8").write(css.strip() + "\n")
    open(os.path.join(HUB, "engine.js"), "w", encoding="utf-8").write(engine_js)
    return data_block


def js_str(s):
    """Encode a python string as a JS template literal (backtick) safely."""
    return "`" + s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${") + "`"


def main():
    data_block = extract_engine()
    # CDS-Start-Here stays SELF-CONTAINED (it is the template + the proven page). The shared
    # engine is derived from it for the other four modules. Save its data block as the
    # gold-standard example authors follow for the other systems' data.js.
    open(os.path.join(HUB, "cds-data-example.js"), "w", encoding="utf-8").write(data_block + "\n")
    print("wrote Integral-Data-Start-Here/cds-data-example.js (authoring reference)")
    # thin index.html for the engine-based modules (those with a data.js, i.e. not CDS)
    for d in MODULE_DIRS:
        if d == "CDS-Start-Here":
            continue
        dj = os.path.join(ROOT, d, "data.js")
        if os.path.exists(dj):
            txt = open(dj, encoding="utf-8").read()
            emoji = (re.search(r'emoji:\s*"([^"]+)"', txt) or [None, ""])[1]
            title = (re.search(r'title:\s*"([^"]+· Start Here)"', txt) or [None, "Start Here"])[1]
            page = THIN_INDEX.replace("<title>Start Here — Integral</title>",
                                      f"<title>{emoji} {title} — Integral</title>")
            open(os.path.join(ROOT, d, "index.html"), "w", encoding="utf-8").write(page)
            print(f"wrote {d}/index.html (thin) — title: {emoji} {title}")
        else:
            print(f"-- {d}: no data.js yet (skipped)")
    print("engine.css + engine.js written to Integral-Data-Start-Here/")


if __name__ == "__main__":
    main()
